spring:
  application:
    name: user-service
  graphql:
    schema:
      file-extensions: graphql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_IP}:3306/graphql?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Seoul
      serialization:
        fail-on-empty-beans: false
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
